spring:
  datasource:
    url: jdbc:mysql://zet-2.c3s6mmmia1ss.ap-northeast-2.rds.amazonaws.com:3306/crate?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: daf6JaPZjCqafrdwAF1m
    driver-class-name: com.mysql.cj.jdbc.Driver
