spring:
  application:
    name: cokeZet
  profiles:
    include: oauth, database, jwt

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true