spring:
  application:
    name: cokeZet
  config:
    import:
      - classpath:config/application-database.yml
      - classpath:config/application-jwt.yml
      - classpath:config/application-oauth.yml
  profiles:
    group:
      local: oauth, database, jwt
      dev: oauth, database, jwt
      prod: oauth, database, jwt