spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
        provider:
          google:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          apple:
            issuer-uri: https://appleid.apple.com
            jwk-set-uri: https://appleid.apple.com/auth/keys

# Apple 로그인 관련 설정
apple:
  team-id: ${APPLE_TEAM_ID}
  client-id: ${APPLE_CLIENT_ID} # Services ID와 동일
  key-id: ${APPLE_KEY_ID}
  private-key: ${APPLE_PRIVATE_KEY}